# Generated by Django 5.0.1 on 2024-04-16 00:06

import api.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_leasedetails_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasedetails',
            name='agreement_number',
            field=models.BigAutoField(default=api.utils.utils.generate_unique_integer_number, editable=False, help_text='Unique 12-digit agreement number', primary_key=True, serialize=False),
        ),
    ]
